export const CURRENCY_DETAILS_ACTION_TYPE  = {
    GET_DATA_FOR_GIVEN_MONTH_BY_CURRENCY: 'GET_DATA_FOR_GIVEN_MONTH_BY_CURRENCY',
    READY_DATA_FOR_GIVEN_MONTH: 'READY_DATA_FOR_GIVEN_MONTH',
    CLEAR_DATA: 'CLEAR_DATA',
    CLEAR_ERROR: 'CLEAR_ERROR',
    TASK_STATUS: 'TASK_STATUS',
    SET_CHOSEN_MONTH: 'SET_CHOSEN_MONTH',
    SET_CHOSEN_YEAR: 'SET_CHOSEN_YEAR', 
}

export const CURRENCY_ACTION_TYPE  = {
    GET_AVERAGE_FOR_GIVEN_MONTH: 'GET_AVERAGE_FOR_GIVEN_MONTH', 
    READY_AVERAGE_FOR_GIVEN_MONTH: 'READY_AVERAGE_FOR_GIVEN_MONTH',
    CLEAR_DATA: 'CLEAR_DATA',
    TASK_STATUS: 'TASK_STATUS',
    SET_CHOSEN_MONTH: 'SET_CHOSEN_MONTH',
    SET_CHOSEN_YEAR: 'SET_CHOSEN_YEAR', 
}

export const TASK_STATUS = {
    NONE: 'NONE',
    PENDING: 'PENDING',
    ERROR: 'ERROR',
    ACCOMPLISHED: 'ACCOMPLISHED'
}

export const API_ERROR = {
    API_ERROR_300: 'API_ERROR_300',
    API_ERROR_400: 'API_ERROR_400',
    API_ERROR_500: 'API_ERROR_500',
    API_ERROR_UNDEFINED: 'API_ERROR_UNDEFINED', 
}

export const MESSAGE_BOX_TYPE = {
    INFO: 'INFO',
    ERROR: 'ERROR'
}

export const SORT_FIELD_TYPE ={
    DATE: 'DATE',
    BUY: 'BUY',
    SELL: 'SELL'
}

export const monthDays = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];