export const CURRENCY_DETAILS_ACTION_TYPE  = {
    GET_DATA_FOR_GIVEN_MONTH_BY_CURRENCY: 'GET_DATA_FOR_GIVEN_MONTH_BY_CURRENCY',
    READY_DATA_FOR_GIVEN_MONTH: 'READY_DATA_FOR_GIVEN_MONTH',
    TASK_STATUS: 'TASK_STATUS',
}

export const CURRENCY_ACTION_TYPE  = {
    GET_AVERAGE_FOR_GIVEN_MONTH: 'GET_AVERAGE_FOR_GIVEN_MONTH', 
    READY_AVERAGE_FOR_GIVEN_MONTH: 'READY_AVERAGE_FOR_GIVEN_MONTH',
    TASK_STATUS: 'TASK_STATUS',
}

export const TASK_STATUS = {
    NONE: 'NONE',
    PENDING: 'PENDING',
    ERROR: 'ERROR',
    ACCOMPLISHED: 'ACCOMPLISHED'
}
